### ISSUE TITLE
Inconsistent results between PyPi package, python package installed from repository and web app

### ISSUE THREAD

**Issue by chrippel** [ovidiopr/scattnlay#75]
Dear devs,
i was having some trouble reproducing some Mie results with you PyPi package. After some digging i found an inconsistency between the PyPi package, the python package installed from the github repository and the web app.

minimal examples:
a)  a sphere with static n=1.4727 + 0.00001j with radius 400nm at wavelength 800nm:
- same result using your web app and the python package install from the repository (version 2.3)
- different result using the PyPi installation (also version 2.3)

b)  same sphere with static (n=1.4727 + 0.00001j with radius 400nm) at wavelength 8000 nm:
- all 3 methods give the same result

I used the exact same script with the python packages (PyPi vs GitHub) so I assume there is a  bug somewhere in the PyPi package .

Christian

**Comment by kostyfisik** [comment]
This is an old bug that was fixed in GitHub version long ago, it was happening when R/lambda=1/2 for any value of refractive index. More details on this you can find here https://github.com/ovidiopr/scattnlay/blob/master/tests/test_bulk_sphere.cc#L11-L34 . Web app and PyPi use exactly the same core compuational code, but web app is a more recent one. Bumped GitHub version to make them easier to distinguish.  @ovidiopr Could you please update PyPi version?

**Comment by chrippel** [comment]
Thanks for the quick response!
An updated PyPi package would indeed be appreciated.

**Comment by ovidiopr** [comment]
Sorry for the long time to respond. I have been busy with other projects. PyPi package is now updated.

**Comment by chrippel** [comment]
Thank you!
